# Configuration for the public "Keyflow" Shopify app.
client_id = "9f44cdb0d3e56958fd1ad1850931e480"
name = "Keyflow"
application_url = "https://app-production-51af.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
scopes = "read_orders,read_products"

[auth]
redirect_urls = [
  "https://app-production-51af.up.railway.app/auth/callback",
  "https://app-production-51af.up.railway.app/auth/shopify/callback",
  "https://app-production-51af.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/paid"
  topics = ["orders/paid"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = ["orders/create"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = ["customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = ["customers/redact"]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = ["shop/redact"]

[pos]
embedded = false
